
const state={products:[],cart:JSON.parse(localStorage.getItem('gravixCart')||'[]'),wishlist:JSON.parse(localStorage.getItem('gravixWishlist')||'[]')};
const save=()=>{localStorage.setItem('gravixCart',JSON.stringify(state.cart));localStorage.setItem('gravixWishlist',JSON.stringify(state.wishlist));count()};
const count=()=>{const e=document.getElementById('cartCount');if(e)e.textContent=state.cart.reduce((a,b)=>a+b.qty,0)};
const toast=m=>{let t=document.querySelector('.toast');if(!t){t=document.createElement('div');t.className='toast';document.body.appendChild(t)}t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1300)};
const addToCart=id=>{const x=state.cart.find(i=>i.id===id);x?x.qty++:state.cart.push({id,qty:1});save();toast('Added to cart')};
const toggleWish=id=>{state.wishlist=state.wishlist.includes(id)?state.wishlist.filter(x=>x!==id):[...state.wishlist,id];save();toast(state.wishlist.includes(id)?'Saved to favorites':'Removed from favorites')};
const card=p=>`<article class="card"><div class="badge">${p.id%4===0?'Best Seller':p.id%4===1?'New':p.id%4===2?'Popular':'Featured'}</div><button class="wish" onclick="toggleWish(${p.id})">♡</button><a class="pic" href="product.html?id=${p.id}"><img src="${p.image}" alt="${p.image_alt||p.name}" loading="lazy"></a><div class="rating">★★★★★ <span>(${p.reviews})</span></div><h3>${p.name}</h3><div class="price">$${Number(p.price).toFixed(2)}</div><button class="add" onclick="addToCart(${p.id})">Add to Cart</button></article>`;
async function load(){const r=await fetch('products.json');state.products=await r.json();setupFilters();renderShop();renderProduct();renderCart();renderWishlist()}
function setupFilters(){const c=document.getElementById('catFilter'),s=document.getElementById('sizeFilter'),f=document.getElementById('finishFilter');if(c){[...new Set(state.products.map(p=>p.category))].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;c.appendChild(o)})}if(s){[...new Set(state.products.map(p=>p.size).filter(Boolean))].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;s.appendChild(o)})}if(f){[...new Set(state.products.map(p=>p.finish).filter(Boolean))].sort().forEach(v=>{const o=document.createElement('option');o.value=v;o.textContent=v;f.appendChild(o)})}['shopSearch','catFilter','sizeFilter','finishFilter','sort'].forEach(id=>document.getElementById(id)?.addEventListener('input',renderShop));document.getElementById('search')?.addEventListener('keydown',e=>{if(e.key==='Enter')location.href='shop.html?search='+encodeURIComponent(e.target.value)})}
function renderShop(){const g=document.getElementById('shopGrid');if(!g)return;const q=(document.getElementById('shopSearch')?.value||new URLSearchParams(location.search).get('search')||'').toLowerCase();const cat=document.getElementById('catFilter')?.value||new URLSearchParams(location.search).get('cat')||'';const size=document.getElementById('sizeFilter')?.value||'';const finish=document.getElementById('finishFilter')?.value||'';const sort=document.getElementById('sort')?.value||'featured';let a=state.products.filter(p=>(!q||(p.name+' '+p.category+' '+p.size+' '+p.vehicle).toLowerCase().includes(q))&&(!cat||p.category===cat)&&(!size||p.size===size)&&(!finish||p.finish===finish));if(sort==='price-low')a.sort((x,y)=>x.price-y.price);if(sort==='price-high')a.sort((x,y)=>y.price-x.price);if(sort==='name')a.sort((x,y)=>x.name.localeCompare(y.name));g.innerHTML=a.map(card).join('')}
function renderProduct(){const e=document.getElementById('productDetail');if(!e)return;const id=Number(new URLSearchParams(location.search).get('id')||0);const p=state.products.find(x=>x.id===id)||state.products[0];e.innerHTML=`<div class="detail"><div class="detail-photo"><img src="${p.image}" alt="${p.image_alt||p.name}"></div><div class="detail-info"><div class="eyebrow">${p.category}</div><h1>${p.name}</h1><div class="rating">★★★★★ (${p.reviews})</div><div class="detail-price">$${p.price.toFixed(2)}</div><p style="line-height:1.8;color:#9aa2a8">${p.description}</p><div style="background:#12181d;border-left:3px solid #ff171e;padding:12px;color:#cdd2d6"><strong>Fitment Note</strong><br>${p.details}</div><div class="specs"><div class="spec"><small>Type</small><strong>${p.type}</strong></div><div class="spec"><small>Size</small><strong>${p.size||'—'}</strong></div><div class="spec"><small>Finish</small><strong>${p.finish||'—'}</strong></div><div class="spec"><small>Vehicle</small><strong>${p.vehicle}</strong></div><div class="spec"><small>Season</small><strong>${p.season||'—'}</strong></div><div class="spec"><small>Terrain</small><strong>${p.terrain||'—'}</strong></div></div><button class="btn" onclick="addToCart(${p.id})">Add to Cart</button><a class="btn alt" href="contact.html">Ask Support</a></div></div>`}
function renderCart(){const e=document.getElementById('cartPage');if(!e)return;if(!state.cart.length){e.innerHTML='<p style="color:#9aa2a8">Your cart is empty.</p><a class="btn" href="shop.html">Keep Shopping →</a>';return}let t=0;e.innerHTML=state.cart.map(i=>{const p=state.products.find(x=>x.id===i.id);if(!p)return'';t+=p.price*i.qty;return `<div style="display:flex;gap:11px;align-items:center;background:#fff;color:#111;padding:10px;margin:7px 0;border-radius:4px"><img src="${p.image}" style="width:88px;height:88px;object-fit:contain"><div style="flex:1"><strong>${p.name}</strong><div>Qty ${i.qty}</div></div><div>$${(p.price*i.qty).toFixed(2)} <button onclick="state.cart=state.cart.filter(x=>x.id!==${i.id});save();renderCart()">Remove</button></div></div>`}).join('')+`<h2>Total: $${t.toFixed(2)}</h2><button class="btn" onclick="toast('Checkout demo ready')">Checkout</button>`}
function renderWishlist(){const e=document.getElementById('wishlistPage');if(!e)return;const a=state.products.filter(p=>state.wishlist.includes(p.id));e.innerHTML=a.length?`<div class="grid">${a.map(card).join('')}</div>`:'<p style="color:#9aa2a8">Nothing saved yet.</p>'}
count();load();
